from . import gif_typifications_purchase
from . import gif_hr_employee_inherit
from . import gif_product_template_inherit
from . import gif_purchase_order_inherit
from . import gif_account_move_inherit
from . import gif_account_payment_inherit
from . import gif_account_batch_payment_inherit
from . import gif_purchase_requisition_inherit
from . import gif_payment_register_inherit