from . import gif_fill_rate
from . import gif_sale_order
from . import gif_stock_picking
from . import gif_stock_picking_batch
from . import gif_stock_move
from . import gif_stock_move_line
from . import gif_account_move
from . import gif_account_payment
from . import gif_account_batch_payment
